local tools = {
    "bash-language-server",
    "ansible-language-server",
    "editorconfig-checker",
    -- "pyright",
    -- "terraform-ls",
    -- "clangd",
    -- "rust-analyzer",
    -- "solargraph",
    "vim-language-server",
    "dockerfile-language-server",
    "html-lsp",
    "typescript-language-server",
    "lua-language-server",
    "stylua",
    -- "jsonnet-language-server",
    -- "gopls",
    -- "delve",
    -- "gofumpt",
    -- "goimports",
    -- "goimports-reviser",
    -- "golangci-lint",
    -- "golangci-lint-langserver",
    -- "golines",
    -- "gomodifytags",
    -- "gotests",
    -- "gotestsum",
    -- "iferr",
    -- "impl",
    "marksman",
    "prettier",
    "angular-language-server",
    "codelldb",
    "codespell",
    "css-lsp",
    "custom-elements-languageserver",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "emmet-ls",
    "eslint_d",
    "firefox-debug-adapter",
    "flake8",
    "google-java-format",
    "java-debug-adapter",
    "java-test",
    "jdtls",
    "js-debug-adapter",
    "json-lsp",
    "lemminx",
    "lua-language-server",
    "prisma-language-server",
    "pyright",
    "rust-analyzer",
    "rustfmt",
    "stylelint",
    "tailwindcss-language-server",
    "vue-language-server",
    "xmlformatter",
    "yaml-language-server"
}
require("mason-lspconfig").setup()
require("mason-tool-installer").setup({
    ensure_installed = tools,
})
